version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: log-postgres
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"        # свободен
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d logdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7-jammy
    container_name: log-mongodb
    environment:
      MONGO_INITDB_DATABASE: logdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"      # свободен
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: log-kafka
    environment:
      # KRaft режим (без ZooKeeper)
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      # Адрес для внешних подключений (ваше приложение будет подключаться по localhost)
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092" # внутри сети
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: "1"
      KAFKA_CFG_NODE_ID: "1"
      # Увеличиваем лимиты для стабильности
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    ports:
      - "9092:9092"       # свободен
    volumes:
      - kafka_data:/bitnami/kafka
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 15s
      timeout: 10s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log-processor-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/logdb
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_KAFKA_TOPIC_RAW_EVENTS: raw-events
      APP_KAFKA_CONSUMER_GROUP_ID: log-processor-group
    ports:
      - "8081:8080"        # внешний порт 8081, внутренний 8080
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  kafka_data: