spring:
  application:
    name: log-processor

  datasource:
    url: jdbc:postgresql://localhost:5432/logdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # Flyway управляет схемой
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/logdb

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:io.github.bugrov.log_processor.api.dto.LogEventMessage
    consumer:
      group-id: log-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: event:io.github.bugrov.log_processor.api.dto.LogEventMessage

# Настройки приложения
app:
  kafka:
    topic:
      raw-events: raw-events
    consumer:
      group-id: log-processor-group

# Actuator (тумблер)
management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown
  endpoint:
    shutdown:
      enabled: true

# Логирование
logging:
  level:
    io.github.bugrov: DEBUG
    org.springframework.kafka: INFO